### ISSUE TITLE
"Water buoyancy" section -- is it wallclimbing?

### ISSUE THREAD

**Issue by ParaLogia** [deynarde/kag-knight-compendium#2]
The **Water buoyancy** section under Mobility says "_As you rise up through water you receive a significant speed boost._" This would imply that you naturally gain a lot of speed just by moving up through water.

But in my experience, you only get this speed boost if you **wall-climb** while underwater. Is this an oversight in the description, or am I mistaken?

**Comment by deynarde** [comment]
Yes, you're right, I updated the description.
